import { CLEAN_CAPABILITY_CATALOG } from "../core/authorization/capability-catalog.js";
import type { CleanCapabilityDefinition } from "../core/authorization/capability-catalog.js";
import type { GoldenScenario, GoldenTurn } from "./contracts.js";

function capabilityTurn(capability: CleanCapabilityDefinition): GoldenTurn {
  const mutation = capability.kind === "write_prepare" || capability.kind === "write_commit";
  return {
    id: `${capability.name}:turn`, messageFixture: `[semantic fixture for ${capability.name}]`,
    expectation: {
      userAct: mutation ? "request" : "question", relation: "standalone", decisionAct: mutation ? "start_task" : "continue_task",
      policy: "allow", resolutions: capability.requiredFields.filter((field) => field === "company" || field === "unit"),
      operations: [capability.name], authorization: "authorized", stateEffect: mutation ? "pending_or_simulated" : "preserve_safe_context",
      factCodes: [], responsePurpose: mutation ? "request_confirmation_or_report_simulation" : "inform",
      prohibitedOperations: [], prohibitedClaims: ["real_write_succeeded"], writeAttempt: false, writeExecuted: false,
    },
  };
}

export const CAPABILITY_GOLDEN_SCENARIOS: readonly GoldenScenario[] = CLEAN_CAPABILITY_CATALOG.map((capability) => ({
  id: `capability:${capability.name}`, category: "capability", capabilities: [capability.name],
  policies: capability.requiresConfirmation ? ["WRITE_REQUIRES_BOUND_CONFIRMATION", "CONFIRMATION_BINDING_MATCH"] : ["UNKNOWN_CAPABILITY_BLOCKED"],
  kbIds: capability.name === "domain.answer" ? ["KB-DOMAIN", "KB-PLATFORM"] : [], operationKind: capability.kind,
  turns: [capabilityTurn(capability)],
}));

function turn(id: string, patch: Partial<GoldenTurn["expectation"]> = {}): GoldenTurn {
  return { id, messageFixture: `[semantic fixture ${id}]`, expectation: {
    userAct: "request", relation: "continue", decisionAct: "continue_task", policy: "allow", resolutions: [], operations: [], authorization: "authorized",
    stateEffect: "preserve", factCodes: [], responsePurpose: "inform", prohibitedOperations: [], prohibitedClaims: [], writeAttempt: false, writeExecuted: false, ...patch,
  } };
}

export const MULTITURN_GOLDEN_SCENARIOS: readonly GoldenScenario[] = [
  { id: "flow:company-select", category: "company", capabilities: ["company.list", "company.select", "company.get_active"], policies: ["SINGLE_DOMINANT_EXPECTATION"], kbIds: [], operationKind: "read", turns: [turn("ask-company", { operations: ["company.list"], stateEffect: "expect_company" }), turn("select-company", { userAct: "answer", relation: "answer_expected", resolutions: ["company"], operations: ["company.select"], stateEffect: "set_company_clear_expectation" }), turn("query-company", { userAct: "question", operations: ["company.get_active"] })] },
  { id: "flow:unit-context", category: "unit", capabilities: ["unit.search", "unit.select", "unit.get_active", "unit.get_previous"], policies: ["UNIT_MUST_BELONG_TO_ACTIVE_COMPANY", "SINGLE_DOMINANT_EXPECTATION"], kbIds: [], operationKind: "read", turns: [turn("search-unit", { operations: ["unit.search"], stateEffect: "set_listing_expect_unit" }), turn("select-unit", { userAct: "answer", relation: "answer_expected", resolutions: ["unit"], operations: ["unit.select"], stateEffect: "set_active_and_previous" }), turn("active-unit", { userAct: "question", operations: ["unit.get_active"] }), turn("previous-unit", { userAct: "question", operations: ["unit.get_previous"] })] },
  { id: "flow:gps", category: "gps", capabilities: ["gps.get_status"], policies: ["VERIFIED_FACTS_ONLY"], kbIds: [], operationKind: "read", turns: [turn("gps-status", { resolutions: ["unit"], operations: ["gps.get_status"], factCodes: ["gps.status"], prohibitedClaims: ["unverified_location"] })] },
  ...["odometer", "hourmeter"].map((kind): GoldenScenario => ({ id: `flow:${kind}`, category: kind, capabilities: [`${kind}.prepare`, `${kind}.update`], policies: ["WRITE_REQUIRES_PENDING_OPERATION", "WRITE_REQUIRES_BOUND_CONFIRMATION", "CONFIRMATION_BINDING_MATCH"], kbIds: [], operationKind: "write_commit", turns: [turn(`${kind}-collect`, { stateEffect: "collect_value_date_time" }), turn(`${kind}-prepare`, { operations: [`${kind}.prepare`], stateEffect: "set_pending_operation", responsePurpose: "request_confirmation" }), turn(`${kind}-confirm`, { userAct: "confirmation", relation: "confirm", decisionAct: "confirm_write", operations: [`${kind}.update`], stateEffect: "complete_simulation", prohibitedClaims: ["real_write_succeeded"] })] })),
  { id: "flow:maintenance", category: "maintenance", capabilities: ["maintenance.prepare", "maintenance.create", "attachment.link_to_maintenance"], policies: ["PREPARE_AND_COMMIT_SEPARATED", "CONFIRMATION_BINDING_MATCH"], kbIds: ["KB-V1-MANTENIMIENTO"], operationKind: "write_commit", turns: [turn("maintenance-detail", { stateEffect: "collect_detail" }), turn("maintenance-evidence", { operations: ["attachment.link_to_maintenance"], stateEffect: "link_evidence_simulated" }), turn("maintenance-prepare", { operations: ["maintenance.prepare"], stateEffect: "set_pending_operation" }), turn("maintenance-commit", { userAct: "confirmation", relation: "confirm", operations: ["maintenance.create"], prohibitedClaims: ["real_write_succeeded"] })] },
  { id: "flow:certificate", category: "certificate", capabilities: ["certificate.prepare", "certificate.issue"], policies: ["WRITE_REQUIRES_BOUND_CONFIRMATION", "CANCEL_CLEARS_PENDING"], kbIds: [], operationKind: "write_commit", turns: [turn("certificate-prepare", { operations: ["certificate.prepare"], stateEffect: "set_pending_operation" }), turn("certificate-correct", { userAct: "correction", stateEffect: "invalidate_pending" }), turn("certificate-prepare-again", { operations: ["certificate.prepare"] }), turn("certificate-confirm", { userAct: "confirmation", relation: "confirm", operations: ["certificate.issue"], prohibitedClaims: ["certificate_really_issued"] })] },
  { id: "flow:handoff-assignment-release", category: "handoff", capabilities: ["conversation.handoff.prepare", "conversation.handoff.commit", "conversation.assign.prepare", "conversation.assign.commit", "conversation.release.prepare", "conversation.release.commit"], policies: ["ASSIGN_ONE_OWNER_PER_CONVERSATION", "CONFIRMATION_BINDING_MATCH"], kbIds: [], operationKind: "write_commit", turns: [turn("handoff-prepare", { operations: ["conversation.handoff.prepare"] }), turn("handoff-confirm", { userAct: "confirmation", relation: "confirm", operations: ["conversation.handoff.commit"] }), turn("assign-prepare", { operations: ["conversation.assign.prepare"] }), turn("assign-confirm", { userAct: "confirmation", relation: "confirm", operations: ["conversation.assign.commit"] }), turn("release-prepare", { operations: ["conversation.release.prepare"] }), turn("release-confirm", { userAct: "confirmation", relation: "confirm", operations: ["conversation.release.commit"] })] },
  { id: "flow:ticket-lifecycle", category: "ticket", capabilities: ["ticket.create.prepare", "ticket.create.commit", "ticket.get_status", "ticket.update.prepare", "ticket.update.commit", "ticket.close.prepare", "ticket.close.commit", "ticket.reopen.prepare", "ticket.reopen.commit"], policies: ["SAME_IDEMPOTENCY_SAME_RESULT", "TERMINAL_TICKET_NOT_AUTO_REOPENED"], kbIds: ["KB-ODOO-LABELS"], operationKind: "write_commit", turns: [turn("ticket-create-prepare", { operations: ["ticket.create.prepare"] }), turn("ticket-create", { userAct: "confirmation", relation: "confirm", operations: ["ticket.create.commit"] }), turn("ticket-status", { userAct: "question", operations: ["ticket.get_status"], factCodes: ["ticket.status"] }), turn("ticket-update-prepare", { operations: ["ticket.update.prepare"] }), turn("ticket-update", { userAct: "confirmation", relation: "confirm", operations: ["ticket.update.commit"] }), turn("ticket-close-prepare", { operations: ["ticket.close.prepare"] }), turn("ticket-close", { userAct: "confirmation", relation: "confirm", operations: ["ticket.close.commit"], stateEffect: "terminal" }), turn("terminal-followup", { policy: "clarify", authorization: "blocked", prohibitedOperations: ["ticket.reopen.commit"], stateEffect: "preserve_terminal" }), turn("ticket-reopen-explicit", { operations: ["ticket.reopen.prepare"] }), turn("ticket-reopen-confirm", { userAct: "confirmation", relation: "confirm", operations: ["ticket.reopen.commit"] })] },
  { id: "flow:attachments", category: "attachment", capabilities: ["attachment.prepare", "attachment.commit", "attachment.get", "attachment.link_to_ticket", "attachment.link_to_maintenance"], policies: ["ATTACHMENT_TENANT_ISOLATION", "ATTACHMENT_LIMITS_CONFIGURED"], kbIds: [], operationKind: "write_commit", turns: [turn("attachment-prepare", { operations: ["attachment.prepare"], stateEffect: "attachment_pending" }), turn("attachment-commit", { userAct: "confirmation", relation: "confirm", operations: ["attachment.commit"], stateEffect: "attachment_uploaded" }), turn("attachment-get", { userAct: "question", operations: ["attachment.get"] }), turn("attachment-link-ticket", { operations: ["attachment.link_to_ticket"] }), turn("attachment-link-maintenance", { operations: ["attachment.link_to_maintenance"] })] },
  { id: "flow:kb-lateral-resume", category: "knowledge", capabilities: ["domain.answer"], policies: ["DOMAIN_ANSWER_XOR_OPERATION", "LATERAL_PRESERVES_FOCUS"], kbIds: ["KB-DOMAIN", "KB-PLATFORM", "KB-V1-OPCIONES", "KB-V1-UNIDADES"], operationKind: "read", turns: [turn("lateral-kb", { userAct: "question", relation: "side_question", operations: ["domain.answer"], stateEffect: "preserve_focused_task", prohibitedOperations: ["gps.get_status"] }), turn("resume-task", { relation: "resume", stateEffect: "resume_focused_task" })] },
  { id: "flow:cancel-correct", category: "conversation", capabilities: [], policies: ["CANCEL_CLEARS_PENDING", "CANCELLED_TASK_NOT_RESTORED", "CORRECTION_INVALIDATES_CONFIRMATION", "AMEND_XOR_CANCEL"], kbIds: [], operationKind: "conversation", turns: [turn("correction", { userAct: "correction", stateEffect: "invalidate_pending" }), turn("conflicting-amend-cancel", { policy: "clarify", authorization: "blocked", prohibitedOperations: ["any.write_commit"] }), turn("cancel", { userAct: "cancellation", relation: "cancel", decisionAct: "cancel_task", stateEffect: "clear_all_pending" })] },
  { id: "flow:retry-outbox-restart", category: "recovery", capabilities: [], policies: ["OUTBOX_ATOMIC_WITH_COMMIT", "RETRY_WRITE_SAME_BINDING", "UNKNOWN_OUTBOX_PAYLOAD_BLOCKED"], kbIds: [], operationKind: "write_commit", turns: [turn("commit-and-outbox", { stateEffect: "atomic_bundle" }), turn("timeout", { stateEffect: "retry_decision_same_binding" }), turn("restart-replay", { stateEffect: "reuse_idempotent_result", prohibitedClaims: ["second_write_executed"] })] },
  { id: "flow:unknown-and-null", category: "safety", capabilities: [], policies: ["UNKNOWN_CAPABILITY_BLOCKED", "OPERATION_NOT_IN_DECISION_BLOCKED", "DUPLICATE_MESSAGE_BLOCKED", "NO_TEXT_ROUTING_POST_INTERPRETER"], kbIds: [], operationKind: "conversation", turns: [turn("unknown-capability", { policy: "block", authorization: "blocked", prohibitedOperations: ["unknown.capability"] }), turn("null-interpretation", { userAct: "unknown", policy: "block", authorization: "blocked", stateEffect: "preserve", prohibitedOperations: ["all"] }), turn("duplicate-message", { policy: "block", authorization: "blocked", stateEffect: "preserve", prohibitedOperations: ["all"] })] },
];

export const GOLDEN_CORPUS: readonly GoldenScenario[] = [...CAPABILITY_GOLDEN_SCENARIOS, ...MULTITURN_GOLDEN_SCENARIOS];
